version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: janisuhanda
      POSTGRES_PASSWORD: janisuhanda
      POSTGRES_DB: todoApp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: